# Generated by Django 3.2.6 on 2022-01-19 10:19

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Devices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='裝置名稱')),
            ],
        ),
        migrations.CreateModel(
            name='Properties',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, max_length=20, null=True, verbose_name='資料名稱')),
                ('value', models.CharField(blank=True, max_length=20, null=True, verbose_name='資料數值')),
                ('create_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='資料建立時間')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devices.devices', verbose_name='相依裝置')),
            ],
        ),
    ]
