# Generated by Django 3.2.6 on 2022-01-11 08:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='APIsAccessControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'APIsAccessControl - [APIs 存取控制]',
                'verbose_name_plural': 'APIsAccessControl - [APIs 存取控制]',
            },
        ),
        migrations.CreateModel(
            name='APIsGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=65535, unique=True, verbose_name='API群組名稱')),
                ('group_describe', models.TextField(blank=True, default=None, null=True, verbose_name='API群組說明')),
                ('user', models.ManyToManyField(blank=True, default=None, null=True, related_name='user_api_group', through='common.APIsAccessControl', to=settings.AUTH_USER_MODEL, verbose_name='相依 User')),
            ],
            options={
                'verbose_name': 'APIGroup - [APIs 群組]',
                'verbose_name_plural': 'APIGroup - [APIs 群組]',
            },
        ),
        migrations.CreateModel(
            name='APIsObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewsets_name', models.CharField(max_length=65535, unique=True, verbose_name='API Viewsets Name')),
                ('display_name', models.CharField(max_length=65535, verbose_name='API Display Name')),
            ],
            options={
                'verbose_name': 'APIsObject - [API 物件]',
                'verbose_name_plural': 'APIsObject - [API 物件]',
            },
        ),
        migrations.CreateModel(
            name='APIsMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_method', models.BooleanField(verbose_name='list 方法')),
                ('retrieve_method', models.BooleanField(verbose_name='retrieve 方法')),
                ('create_method', models.BooleanField(verbose_name='create 方法')),
                ('update_method', models.BooleanField(verbose_name='update 方法')),
                ('partial_update_method', models.BooleanField(verbose_name='partial_update 方法')),
                ('destroy_method', models.BooleanField(verbose_name='destroy 方法')),
                ('apis_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apimethod_apis_group', to='common.apisgroup', verbose_name='相依 APIsGroup')),
                ('apis_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apimethod_apis_object', to='common.apisobject', verbose_name='相依 APIsObject')),
            ],
            options={
                'verbose_name': 'APIsMethod - [API 功能]',
                'verbose_name_plural': 'APIsMethod - [API 功能]',
            },
        ),
        migrations.AddField(
            model_name='apisaccesscontrol',
            name='apisgroup',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.apisgroup', verbose_name='相依 APIsGroup'),
        ),
        migrations.AddField(
            model_name='apisaccesscontrol',
            name='user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='相依 User'),
        ),
    ]
