# Generated by Django 3.2.6 on 2022-01-18 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='姓名')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('sex', models.IntegerField(blank=True, choices=[(None, '(Unknown)'), (0, 'Female'), (1, 'Male')], null=True)),
                ('birthday', models.DateField()),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Employee - [員工]',
                'verbose_name_plural': 'Employee - [員工]',
            },
        ),
    ]
