# Generated by Django 3.2.6 on 2022-01-18 07:29

from django.db import migrations
from psqlextra.backend.migrations.operations import PostgresAddRangePartition

class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_auto_20220118_1526'),
    ]

    operations = [
        PostgresAddRangePartition(
            model_name="EmployeePartitione",
            name="employee_partitioned_birthday_1990_to_1991",
            from_values='1990-01-01',
            to_values='1991-12-31',
        ),
    ]
