# Generated by Django 3.2.6 on 2022-01-18 07:30

from django.db import migrations
from psqlextra.backend.migrations.operations.add_range_partition import PostgresAddRangePartition


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_auto_20220118_1529'),
    ]

    operations = [
        PostgresAddRangePartition(
            model_name="EmployeePartitione",
            name="employee_partitioned_birthday_1992_to_1993",
            from_values='1992-01-01',
            to_values='1993-12-31',
        ),
    ]
