# Generated by Django 3.2.6 on 2022-01-18 07:32

from django.db import migrations
from psqlextra.backend.migrations.operations.add_range_partition import PostgresAddRangePartition


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_auto_20220118_1530'),
    ]

    operations = [
        PostgresAddRangePartition(
            model_name="EmployeePartitione",
            name="employee_partitioned_birthday_1994_to_1995",
            from_values='1994-01-01',
            to_values='1995-12-31',
        ),
    ]
