# Generated by Django 3.2.6 on 2022-01-18 07:41

from django.db import migrations
from psqlextra.backend.migrations.operations.add_range_partition import PostgresAddRangePartition


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0005_auto_20220118_1532'),
    ]

    operations = [
        PostgresAddRangePartition(
            model_name="EmployeePartitione",
            name="employee_partitioned_birthday_2020",
            from_values='2020-01-01',
            to_values='2020-12-31',
        ),
    ]
