# Generated by Django 3.2.6 on 2021-12-23 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Iris',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sepal_length', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='花萼長度')),
                ('sepal_width', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='花萼寬度')),
                ('petal_length', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='花瓣長度')),
                ('petal_width', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='花瓣寬度')),
                ('classification', models.CharField(choices=[('setosa', '山鳶尾'), ('versicolor', '變色鳶尾'), ('virginica', '維吉尼亞鳶尾')], default='setosa', max_length=15)),
            ],
            options={
                'verbose_name': 'Iris - [鳶尾花]',
                'verbose_name_plural': 'Iris - [鳶尾花]',
            },
        ),
    ]
