# Generated by Django 3.2.6 on 2022-01-18 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iris', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iris',
            name='classification',
            field=models.CharField(choices=[('setosa', '山鳶尾'), ('versicolor', '變色鳶尾'), ('virginica', '維吉尼亞鳶尾')], default='setosa', max_length=15, verbose_name='分類'),
        ),
    ]
