# Generated by Django 3.2.10 on 2022-05-11 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iris', '0002_alter_iris_classification'),
    ]

    operations = [
        migrations.AddField(
            model_name='iris',
            name='slices',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
