# Generated by Django 3.2.10 on 2022-05-11 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iris', '0003_iris_slices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iris',
            name='slices',
            field=models.PositiveIntegerField(default=0, verbose_name='花瓣片數'),
        ),
    ]
